variables:
    TUTOR_PLUGIN: ecommerce
    TUTOR_IMAGES: ecommerce ecommerce-worker
    TUTOR_PYPI_PACKAGE: tutor-ecommerce
    TUTOR_EXTRA_ENABLED_PLUGINS: discovery
    OPENEDX_RELEASE: koa

include:
  - project: 'community/tutor-ci'
    file: 'plugin-gitlab-ci.yml'
